=== Listeners

The `HttpClient` supports the use of listener objects so that applications can react to certain events in the lifecycle
of an HTTP request.

Listeners can be added to the `HttpClientFactory` or to the `HttpClient` directly. Any listeners registered with the
`HttpClientFactory` will automatically be assigned to any `HttpClient` instance the factory creates. For both objects,
use the `addListener` method to register a listener.

==== Request Listener

Applications may need to intercept an HTTP request directly before the request is actually made to modify the request
parameters. Any request listener that is registered with the `HttpClient` will be called directly before the request
is made.

A great example of a use of this listener is the built-in `BasicAuthListener`, which is an implementation of
`HttpClientRequestListener`.

[source,groovy]
----
// given a client has been created...
client.addListener(new BasicAuthListener('username', 'password'))
----

The `BasicAuthListener` is built with the credentials for the request, and the request is updated with that information
just before the request is actually made.

NOTE: This listener is only called once before the request is made. If retries are automatically attempted, request
listeners will not be called again.

==== Response Listener

The response listener is called after the HTTP request has completed, just before the `HttpResponse` object is passed
back to the caller. Listeners that need to use this functionality should implement the `HttpClientResponseListener`.

NOTE: This listener is only called once after the request is completed. If retries are attempted, response listeners
are called only after all retry attempts have completed.

==== Retry Listener

The retry listener allows applications to determine if a request should be retried based on some criteria. If any
one retry listener determines that the request should be retried, the request will be submitted again until no more
retry listeners request a retry.

Listeners that need to use this functionality should implement the `HttpClientRetryListener` interface.

NOTE: A retry listener may request a retry based on the request, response, and number of previous retries. If one
retry listener does not request a retry, but another one does, the listener that did not request a retry will not
have its `onRetry` method called.

A use case for this functionality is authentication schemes that provide an authentication token that can be reused
until it expires. A retry listener might be created for this type of authentication scheme that inspects the response
of a call to the service that requires the authentication token, and re-authenticates if the previous authentication
token has expired. Once a new authentication token is obtained, the original request can be retried with the updated
authentication token.
