== Changelog

The changelog will be updated with release notes for each release of the library.

2.0.4::

* Update Gradle version and build dependencies.
* Update library dependencies to latest.
* Make `EntityConverterManager` immutable. Converters need to be passed into its constructor going forward.
* Introduce entity converter ordering to ensure that certain converters have higherh or lower priority
  than others.

2.0.3::

* Fix a bug where the reference HTTP client threw an `IOException` when an error HTTP status code was returned
  with no response entity.
* Fix a bug where calling `HttpResponse.getEntity(Class)` threw a `NullPointerException` when no response
  entity was returned.

2.0.2::

* Add `Closeable` support for filters. Any filter that implements `Closeable` are guaranteed to be closed.
* Fix bug where the `LoggingFilter` threw a `NullPointerException` when no request entity is present.
* Do not apply a port if none was specified using the reference HTTP client.

2.0.1::

* Close the underlying Apache HTTP client when the `HttpResponse` is closed.

2.0.0::

The version 2.0 upgrade involved refactoring of the components of the library, with the aim of simplifying
the codebase and making the project more maintainable. Due to this, the change log for this version is
relatively lengthy.

* The library has been ported from Groovy to Java. This was done to remove a required dependency and widen
  the audience that might find value in the library. The Groovy functionality has been moved into its own
  library.
* Changed the Groovy DSL to use a new function-based delegate, bringing it in line with how Groovy DSLs
  typically behave. Before, properties of the `HttpRequest` were assigned as properties. With the change,
  properties are exposed as methods.
* The `EntityConverterManager` is now a required dependency to `HttpClientFactory`. The same manager instance
  is passed along to the `HttpClient` and `HttpResponse` objects to support object marshalling throughout the
  stack. This differs from version 1.0 , where the set of entity converters may be modified in both the
  `HttpClientFactory` and `HttpClient` separately.
* Filters are no longer registered with the `HttpClientFactory` or `HttpClient`, but rather with an
  `HttpRequest`. Since filters act on a request, it brings the registration of filters closer to to the context
  in which they are used.
* Properties that align to specific headers have been removed from the `HttpRequest` and `HttpResponse`. Of
  course, these headers may be added to the request just as any other header would be. In particular, the
  following have been removed:
  ** `contentType`
  ** `accept`
  ** `allow`
* Introduced the `http-requests-groovy` library, which contains the Groovy DSL extensions to `HttpRequest` and
  Groovy specific entity converters.
* Introduced the `http-requests-spring` library, which adds automatic configuration for the various libraries
  contained in the http-requests project.
* Introduced the `http-requests-jackson` library, which adds `Map` and `List` entity converters using Jackson.
* Added `ConvertingHttpEntity` for objects that should be marshalled, so that a content type may also be provided.
* Added a https://github.com/budjb/http-requests-samples[samples project] in GitHub with a collection of example
  applications demonstrating various aspects of the library.
* Removed the Grails 3 plugin.
* Add support for HTTP PATCH. Whether the verb works or not is dependent on the underlying HTTP client.
* Add entity support to HTTP DELETE. Whether this works or not is dependent on the underlying HTTP client *and*
  the HTTP server the request is sent to.
* All artifacts are now deployed to both jcenter and Maven Central.
* Added query parameter support to the `LoggingFilter` (https://github.com/budjb/http-requests/issues/10[#10]).
* Fixed `HttpRequest` clone issue where paths with special characters would cause a URISyntaxException
  (https://github.com/budjb/http-requests/issues/7[#7]).

1.0.2::
* Remove default character set from the `HttpRequest`.
* Change default conversion character set from `UTF-8` to `ISO-8859-1` (per HTTP 1.1 spec).

1.0.1::
* Add missing `@DelegatesTo` annotation to a method taking a closure.
* If a retry filter is registered with the client, the request entity is automatically
  buffered so that it can be resent with subsequent requests.
* Add a reference implementation of the client to avoid the need to include other provider
  implementation modules.
* Made the Grails 3.x plugin compatible with JDK 1.7.
* Modify Grails 3.x plugin so that the classpath scanner prefers the non-built-in HttpClientFactory if another
  provider is found.

1.0.0::
* Initial non-beta release of the library.
