== Entity Converters

Entity converters are responsible for converting request and response entities to and from raw byte arrays. This
prevents applications from having to make separate calls to helper methods or classes to do the conversion.

Much like filter, an entity converter can be registered with both the `HttpClientFactory` and `HttpClient` objects.
Any entity converter registered with the factory will automatically be added to any clients it creates. Entity
converters can be interacted with on both the factory and the client with the following methods.

* `addEntityConverter`
* `removeEntityConveter`
* `getEntityConverters`
* `clearEntityConverters`

=== Entity Readers

Entity readers are responsible for converting the raw byte array of a response entity into some other type of object.
Applications can create a new entity reader for a custom object type that contains the logic to read relevant
information from the byte array entity and create the custom object from it, populated with the data from the response.

Entity reader implementations should implement the `EntityReader` interface.

=== Entity Writers

Entity writers are responsible for converting an object into a raw byte array for use in a request. Much like the entity
readers, entity writers provide applications a method to convert custom objects for use in a request without having to
handle that logic separately from the request call.

Entity writer implementations should implement the `EntityWriter` interface.

NOTE: Entity writers have the option to modify the request by adding the `Content-Type` of the entity it successfully
converted, if a `Content-Type` makes sense. This only happens if a `Content-Type` had not been previously set on the
request.

=== Built-In Converters

The library contains several built-in entity converters that are, by default, automatically registered with all client
instances. Those built-ins include:

* `byte[]` reader and writer.
* `String` reader and writer.
* `GString` writer.
* `Map` reader and writer.
* `List` reader and writer.
* `FormData` reader and writer.
