== Grails Plugin

The Grails 3.x plugin makes using the *http-requests* library with Grails easy. To use the plugin, simply include the
Grails plugin artifact (`com.budjb:http-requests-grails:{version}`) and a provider library.

During initialization, the Grails plugin will automatically locate the `HttpClientFactory` and register it as a Spring
bean with the name `httpClientFactory`. This class can be injected into other managed Spring beans and used without
needing to create the factory manually.

NOTE: The plugin will only use the built-in HTTP client provider if no other provider is found on the classpath.

The plugin also makes it easy to create and use filters and converters. Filters should be created under the
`grails-app/http-filters` directory, and any filter found under that directory will automatically be registered with
the `httpClientFactory` bean. Likewise, any converter found in the `grails-app/http-converters` directory will
automatically be registered with the `httpClientFactory` bean.

NOTE: Filters and converters found in their appropriate directories are registered with the client factory, which will
automatically include those filters and converters in any `HttpClient` that it creates.

TIP: Filters and converters are registered as managed Spring beans as singletons. Other managed Spring beans can be
injected into those filters and converters, much like controllers and services.

There is a small selection of configuration values available to the library, as listed below. These properties can
be assigned under the `httprequests` key in the application configuration.

.Configuration Properties
[grid="rows",cols=[1,1,1,3]
|===
| Name | Type | Default | Description

| `autoLoadFactory`    | `Boolean` | `true` | Whether to automatically locate and register an `HttpClientFactory`
                                              from the classpath. If `false`, applications must manually register
                                              an `HttpClientFactory` with the name `httpClientFactory`, or the
                                              application will fail to start.
| `autoLoadConverters` | `Boolean` | `true` | Whether to automatically register the built-in filters and converters
                                              to the `httpClientFactory`. This does not affect loading filters and
                                              converters found in the `grails-app/http-filters` and
                                              `grails-app/http-converters` directories.
| `scanPackages`       | `List`    |        | Additional classpath packages to scan for `HttpClientFactory` instances.
                                              This is useful when custom providers are used.
|===

The following example can be used to include the plugin. In this example, the bill-of-materials is used and the grails
plugin and the Jersey 1.x provider is included.

.build.gradle
[source,groovy,subs="attributes"]
----
dependencyManagement {
    imports {
        mavenBom "org.grails:grails-bom:$grailsVersion"
        mavenBom "com.budjb:http-requests:{version}"
    }
    applyMavenExclusions false
}

dependencies {
    // ...
    compile "com.budjb:http-requests-grails"
    compile "com.budjb:http-requests-jersey1"
}
----

TIP: Using the bill-of-materials allows the version of the `http-requests` libraries to not require a version.
