== Installing
The library is split into several libraries, which can all be found on https://bintray.com/bintray/jcenter[jCenter]
and https://search.maven.org[Maven Central]. The library contains a core module, which contains the interfaces and base
implementations of the library. There are also libraries that provide support for popular HTTP client libraries, as well
as various extensions that provide additional functionality. The table below lists out all of the libraries that exist
for the HTTP Requests library and what their purposes are.

.HTTP Requests Library Modules
[grid="rows"]
|===
| Module                                | Purpose

| `http-requests-bom`                   | A bill-of-materials POM for all libraries.
| `http-requests-core`                  | Contains the core interfaces of the library, in addition to a built-in HTTP
                                          client implementation built on top of Java's `HttpURLConnection`.
| `http-requests-jersey1`               | Adds support for Jersey 1.x.
| `http-requests-jersey2`               | Adds support for Jersey 2.x.
| `http-requests-httpcomponents-client` | Adds support for Apache HttpComponents Client.
| `http-requests-jackson`               | Adds entity converters for `Map` and `List` types using the Jackson library.
| `http-requests-spring`                | Enables automatic configuration of the HTTP requests components as Spring
                                          beans.
| `http-requests-groovy`                | Adds Groovy DSLs to the library and Groovy-specific entity converters.
|===

NOTE: All modules are deployed under the group `com.budjb`.

As an example, opting to add Jersey 2.x support and Jackson converters, Gradle might be configured like below:

.build.gradle
[source,groovy,subs="attributes"]
----
apply plugin: "java"

repositories {
    mavenCentral()
}

dependencies {
    compile "com.budjb:http-requests-jersey2:{version}"
    compile "com.budjb:http-requests-jackson:{version}"
}
----

Additionally, the bill of materials POM is available to keep dependencies in sync without the need to specify
their version numbers.

.build.gradle
[source,groovy,subs="attributes"]
----
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "io.spring.gradle:dependency-management-plugin:1.0.6.RELEASE"
    }
}

apply plugin: "java"
apply plugin: "io.spring.dependency-management"

repositories {
    mavenCentral()
}

dependencyManagement {
    imports { mavenBom "com.budjb:http-requests-bom:{version}" }
}

dependencies {
    compile "com.budjb:http-requests-jersey2"
    compile "com.budjb:http-requests-jackson"
}
----
