== Introduction
The HTTP Requests library provides a clean and simplified interface to make HTTP requests.

The spirit of this library is to make it trivial to do easy things with HTTP requests. It can accomplish the most
common use cases for an HTTP client, but does not aim to be a complete HTTP client implementation.

At its core, the library defines a framework for making requests. A built-in implementation of this framework based on
Java's built-in HTTP classes is included to make the library extremely lightweight, with its only external dependency
being SLF4J. There are also several providers available that use popular HTTP client libraries, such as Jersey and
Apache HTTP Components Client. When one of these providers is used, the library serves as a facade, making the use of
these popular libraries much easier and your code more concise.

Indeed, the driving philosophy behind this project is to serve as a facade for HTTP requests, so that library authors
may perform HTTP operations without dictating what HTTP library is required, much like SLF4J does for logging.
