=== Creating the Client

An `HttpClient` is used to make requests, but `HttpClient` is an interface and can not be created directly. HTTP client
provider modules provide implementations of `HttpClient` specific to the HTTP client being wrapped. In order to
ensure that authors do not need to worry about what type of `HttpClient` needs to be created, an `HttpClientFactory` can
be used to create the client instances using the `createHttpClient()` method.

The `HttpClientFactory` interface is implemented by provider modules and can be created directly. As an example,
the *Jersey 1.x* module's factory can be used to create a Jersey-specific `HttpClient` instance.

[source,groovy]
def factory = new JerseyHttpClientFactory()
def client = factory.createHttpClient()

TIP: The `HttpClientFactory` can be registered as a singleton Spring bean when applications utilize Spring Framework.
The factory can then be injected as a dependency into other managed Spring beans, and the provider module can be
swapped out transparently and without the need to modify dependent objects. The *Grails 3.x* plugin library does this
work automatically for *Grails 3.x* applications.